# Generated by Django 4.1.3 on 2022-11-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=2)),
                ('date', models.DateField(default='2000-01-01')),
                ('platform', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
