# Generated by Django 4.1.3 on 2022-11-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=None)),
                ('comment', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-01-01')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('country_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.country')),
                ('game_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('game_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
                ('seller_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateField(default=None)),
                ('end_time', models.DateField(default=None)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Develop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.developer')),
                ('game_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=None)),
                ('context', models.CharField(max_length=300)),
                ('likes', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('goods_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.goods')),
                ('order_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
        ),
    ]
