# Generated by Django 4.1.3 on 2022-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_admin_country_developer_order_alter_game_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='goods_id',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='develop',
            old_name='developer_id',
            new_name='developer',
        ),
        migrations.RenameField(
            model_name='develop',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
