# Generated by Django 4.1.3 on 2022-12-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_buyer_id_business_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='2000-01-01')),
                ('players', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='context',
            new_name='content',
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='goods',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='backend.user'),
        ),
        migrations.AddField(
            model_name='goods',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.CharField(default='已上架', max_length=11),
        ),
        migrations.AddField(
            model_name='goods',
            name='steam_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='develop',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.developer'),
        ),
        migrations.AlterField(
            model_name='develop',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='backend.user'),
        ),
        migrations.AlterField(
            model_name='price',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.country'),
        ),
        migrations.AlterField(
            model_name='price',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
