# Generated by Django 4.1.3 on 2022-12-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_heat_tag_rename_context_comment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=2560)),
                ('test', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='comment',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2560)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
    ]
