# Generated by Django 4.1.3 on 2022-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_news_alter_goods_comment_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='target',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='test',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='slide',
            name='url',
            field=models.CharField(default='', max_length=2560),
        ),
    ]
