# Generated by Django 4.1.3 on 2022-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_user_rate_user_bad_user_good_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bad',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='good',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='goods',
            name='cd_key',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='goods',
            name='decription',
            field=models.CharField(default='', max_length=2560),
        ),
        migrations.AlterField(
            model_name='goods',
            name='steam_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
