# Generated by Django 4.1.3 on 2022-12-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_bad_user_dislikes_rename_good_user_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='decription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.CharField(default='', max_length=2560),
        ),
        migrations.AddField(
            model_name='goods',
            name='rating',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='GamePhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2560)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
    ]
