# Generated by Django 4.1.3 on 2022-12-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_decription_goods_description_game_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='description',
            new_name='decription',
        ),
    ]
