# Generated by Django 4.1.3 on 2022-12-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_description_goods_decription'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='discount',
        #     name='user',
        # ),
        migrations.AddField(
            model_name='discount',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.country'),
            preserve_default=False,
        ),
    ]
